language: python
python:
    - "2.7"

# command to install dependencies
install: "pip install -r requirements/development.txt"

# command to run tests
script: coverage run -m nose && flake8

# coverage!
after_success:
    coveralls